-- =====================================================================
-- 06_seed_data.sql: Realistic Seed Data for Development & Testing
-- Seed Passwords are for development only (documented in demo.md)
-- Hashes: Standard ASP.NET Core Identity PBKDF2 with HMAC-SHA256
-- Admin@Pass123! -> AQAAAAIAAYagAAAAEEJ6b6aC0wI9/H+8v...
-- User@Pass123!  -> AQAAAAIAAYagAAAAEIe2l8Z+J/p1gq...
-- =====================================================================

USE `matrimony_hub`;

-- 1. Seed Roles
INSERT INTO `Roles` (`Id`, `Name`, `NormalizedName`, `ConcurrencyStamp`, `Description`) VALUES
(1, 'Admin', 'ADMIN', 'stamp-admin-role', 'System Administrator with complete governance access'),
(2, 'User', 'USER', 'stamp-user-role', 'Registered Matrimonial Member')
ON DUPLICATE KEY UPDATE `Name` = VALUES(`Name`);

-- 2. Seed Admin User (Password: Admin@Pass123!)
-- Hash generated by PasswordHasher<ApplicationUser> for 'Admin@Pass123!'
INSERT INTO `Users` (
    `Id`, `UserName`, `NormalizedUserName`, `Email`, `NormalizedEmail`, 
    `EmailConfirmed`, `PasswordHash`, `SecurityStamp`, `ConcurrencyStamp`, 
    `PhoneNumber`, `PhoneNumberConfirmed`, `TwoFactorEnabled`, `LockoutEnabled`, 
    `AccessFailedCount`, `FullName`, `AccountStatus`, `CreatedAt`, `IsDeleted`
) VALUES (
    1, 'admin@matrimonyhub.com', 'ADMIN@MATRIMONYHUB.COM', 'admin@matrimonyhub.com', 'ADMIN@MATRIMONYHUB.COM',
    1, 'AQAAAAIAAYagAAAAEGGkBkSYdUINgqFZdEF89tlIVedpIxd5FuG4/irKuKUvQeJlk8nRpaVfaSqB4TwNOQ==', 'SECSTAMP001', 'CONCSTAMP001',
    '01700000001', 1, 0, 1, 0, 'System Administrator', 1, '2025-01-01 00:00:00', 0
) ON DUPLICATE KEY UPDATE `PasswordHash` = VALUES(`PasswordHash`), `FullName` = VALUES(`FullName`);

INSERT INTO `UserRoles` (`UserId`, `RoleId`) VALUES (1, 1)
ON DUPLICATE KEY UPDATE `RoleId` = VALUES(`RoleId`);

-- 3. Seed Realistic Normal Users (Password: User@Pass123!)
INSERT INTO `Users` (
    `Id`, `UserName`, `NormalizedUserName`, `Email`, `NormalizedEmail`, 
    `EmailConfirmed`, `PasswordHash`, `SecurityStamp`, `ConcurrencyStamp`, 
    `PhoneNumber`, `PhoneNumberConfirmed`, `TwoFactorEnabled`, `LockoutEnabled`, 
    `AccessFailedCount`, `FullName`, `AccountStatus`, `CreatedAt`, `IsDeleted`
) VALUES 
(2, 'tanvir.ahmed@example.com', 'TANVIR.AHMED@EXAMPLE.COM', 'tanvir.ahmed@example.com', 'TANVIR.AHMED@EXAMPLE.COM', 1, 'AQAAAAIAAYagAAAAEOcu4VWltFI5oTE9TH1DIj0zcKDDKXJcffpZ3ht5lVktKx+WqTyq/KXYEPXqXzzFOw==', 'SECSTAMP002', 'CONCSTAMP002', '01711223344', 1, 0, 1, 0, 'Tanvir Ahmed', 1, '2025-02-01 10:00:00', 0),
(3, 'nusrat.jahan@example.com', 'NUSRAT.JAHAN@EXAMPLE.COM', 'nusrat.jahan@example.com', 'NUSRAT.JAHAN@EXAMPLE.COM', 1, 'AQAAAAIAAYagAAAAEOcu4VWltFI5oTE9TH1DIj0zcKDDKXJcffpZ3ht5lVktKx+WqTyq/KXYEPXqXzzFOw==', 'SECSTAMP003', 'CONCSTAMP003', '01811223344', 1, 0, 1, 0, 'Nusrat Jahan', 1, '2025-02-05 11:30:00', 0),
(4, 'rahim.chowdhury@example.com', 'RAHIM.CHOWDHURY@EXAMPLE.COM', 'rahim.chowdhury@example.com', 'RAHIM.CHOWDHURY@EXAMPLE.COM', 1, 'AQAAAAIAAYagAAAAEOcu4VWltFI5oTE9TH1DIj0zcKDDKXJcffpZ3ht5lVktKx+WqTyq/KXYEPXqXzzFOw==', 'SECSTAMP004', 'CONCSTAMP004', '01911223344', 1, 0, 1, 0, 'Rahim Chowdhury', 1, '2025-02-10 14:15:00', 0),
(5, 'sadia.islam@example.com', 'SADIA.ISLAM@EXAMPLE.COM', 'sadia.islam@example.com', 'SADIA.ISLAM@EXAMPLE.COM', 1, 'AQAAAAIAAYagAAAAEOcu4VWltFI5oTE9TH1DIj0zcKDDKXJcffpZ3ht5lVktKx+WqTyq/KXYEPXqXzzFOw==', 'SECSTAMP005', 'CONCSTAMP005', '01722334455', 1, 0, 1, 0, 'Sadia Islam', 1, '2025-02-15 16:45:00', 0),
(6, 'kazi.farhan@example.com', 'KAZI.FARHAN@EXAMPLE.COM', 'kazi.farhan@example.com', 'KAZI.FARHAN@EXAMPLE.COM', 1, 'AQAAAAIAAYagAAAAEOcu4VWltFI5oTE9TH1DIj0zcKDDKXJcffpZ3ht5lVktKx+WqTyq/KXYEPXqXzzFOw==', 'SECSTAMP006', 'CONCSTAMP006', '01822334455', 1, 0, 1, 0, 'Kazi Farhan', 1, '2025-03-01 09:20:00', 0),
(7, 'anika.tabassum@example.com', 'ANIKA.TABASSUM@EXAMPLE.COM', 'anika.tabassum@example.com', 'ANIKA.TABASSUM@EXAMPLE.COM', 1, 'AQAAAAIAAYagAAAAEOcu4VWltFI5oTE9TH1DIj0zcKDDKXJcffpZ3ht5lVktKx+WqTyq/KXYEPXqXzzFOw==', 'SECSTAMP007', 'CONCSTAMP007', '01922334455', 1, 0, 1, 0, 'Anika Tabassum', 1, '2025-03-05 12:10:00', 0)
ON DUPLICATE KEY UPDATE `FullName` = VALUES(`FullName`);

-- Assign User Roles
INSERT INTO `UserRoles` (`UserId`, `RoleId`) VALUES
(2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2)
ON DUPLICATE KEY UPDATE `RoleId` = VALUES(`RoleId`);

-- 4. Seed Matrimonial Profiles
INSERT INTO `Profiles` (
    `Id`, `UserId`, `FullName`, `Gender`, `DateOfBirth`, `HeightCm`, `WeightKg`,
    `MaritalStatus`, `Religion`, `MotherTongue`, `Nationality`, 
    `HighestEducation`, `Institution`, `Subject`, `GraduationYear`,
    `Occupation`, `Company`, `JobTitle`, `IncomeRange`,
    `Division`, `District`, `City`, `Country`,
    `Smoking`, `Drinking`, `DietaryPreference`, `Hobbies`, `Interests`,
    `AboutMe`, `FamilyInfo`, `PartnerExpectations`, `IsVerified`, `IsActive`, `CreatedAt`
) VALUES
(1, 2, 'Tanvir Ahmed', 1, '1994-05-14', 178, 74, 1, 1, 'Bengali', 'Bangladeshi', 'B.Sc in Computer Science', 'BUET', 'CSE', 2018, 'Software Engineer', 'BrainStation-23', 'Lead Architect', '1.5L - 2.5L BDT', 'Dhaka', 'Dhaka', 'Gulshan', 'Bangladesh', 0, 0, 2, 'Reading, Coding, Chess', 'Tech, Family', 'Practicing Muslim and passionate software engineer living in Dhaka.', 'Respected family in Dhaka with high educational values.', 'Looking for a pious, family-oriented partner with similar values.', 1, 1, '2025-02-01 10:05:00'),
(2, 3, 'Nusrat Jahan', 2, '1997-08-22', 162, 54, 1, 1, 'Bengali', 'Bangladeshi', 'MBBS, FCPS Part-1', 'Dhaka Medical College', 'Medicine', 2021, 'Doctor', 'Square Hospitals', 'Medical Officer', '80K - 1.2L BDT', 'Dhaka', 'Dhaka', 'Dhanmondi', 'Bangladesh', 0, 0, 2, 'Cooking, Travelling, Gardening', 'Healthcare, Travel', 'Dedicated medical doctor from a respected family in Dhaka. Value mutual respect.', 'Father is a retired government director, mother is a teacher.', 'Seeking an educated, kind, and supportive life partner.', 1, 1, '2025-02-05 11:35:00'),
(3, 4, 'Rahim Chowdhury', 1, '1992-11-03', 180, 80, 1, 1, 'Bengali', 'Bangladeshi', 'BBA & MBA in Finance', 'IBA, Dhaka University', 'Finance', 2016, 'Banker', 'Eastern Bank Ltd', 'Senior Manager', '1.2L - 1.8L BDT', 'Chittagong', 'Chittagong', 'Agrabad', 'Bangladesh', 0, 0, 2, 'Swimming, Badminton, Travel', 'Economics, Fitness', 'Grounded, ambitious corporate professional based in Chittagong.', 'Old aristocratic business family in Chittagong.', 'Seeking a warm-hearted, educated partner who values tradition.', 1, 1, '2025-02-10 14:20:00'),
(4, 5, 'Sadia Islam', 2, '1996-03-18', 165, 56, 1, 1, 'Bengali', 'Bangladeshi', 'M.Sc in Architecture', 'BUET', 'Architecture', 2020, 'Architect', 'Studio Morphogenesis', 'Senior Architect', '1.0L - 1.5L BDT', 'Dhaka', 'Dhaka', 'Uttara', 'Bangladesh', 0, 0, 2, 'Painting, Interior Design, Hiking', 'Art, Architecture', 'Creative architect with artistic flair and family values.', 'Father is a businessman, mother is a homemaker.', 'Looking for a broad-minded and supportive husband.', 1, 1, '2025-02-15 16:50:00'),
(5, 6, 'Kazi Farhan', 1, '1995-07-09', 175, 72, 1, 1, 'Bengali', 'Bangladeshi', 'B.Sc in Civil Engineering', 'CUET', 'Civil Engineering', 2019, 'Project Engineer', 'Max Group', 'Project Manager', '90K - 1.4L BDT', 'Sylhet', 'Sylhet', 'Zindabazar', 'Bangladesh', 0, 0, 2, 'Football, Photography, Camping', 'Sports, Travel', 'Friendly, active civil engineer stationed between Sylhet and Dhaka.', 'Loving family living in Sylhet city.', 'Seeking a sincere, kind, and educated partner.', 0, 1, '2025-03-01 09:25:00'),
(6, 7, 'Anika Tabassum', 2, '1998-12-05', 160, 52, 1, 1, 'Bengali', 'Bangladeshi', 'M.A in English Literature', 'University of Dhaka', 'English', 2022, 'Lecturer', 'BRAC University', 'Lecturer', '70K - 1.0L BDT', 'Dhaka', 'Dhaka', 'Banani', 'Bangladesh', 0, 0, 2, 'Literature, Violin, Cafes', 'Books, Culture', 'Academic with a modern outlook and deep moral principles.', 'Parents are both university professors.', 'Seeking a cultured, caring, and honest life partner.', 1, 1, '2025-03-05 12:15:00')
ON DUPLICATE KEY UPDATE `FullName` = VALUES(`FullName`);

-- 5. Seed Profile Photos
INSERT INTO `ProfilePhotos` (`Id`, `UserProfileId`, `PhotoUrl`, `IsPrimary`, `CreatedAt`) VALUES
(1, 1, '/images/groom-1.jpg', 1, '2025-02-01 10:10:00'),
(2, 2, '/images/bride-1.jpg', 1, '2025-02-05 11:40:00'),
(3, 3, '/images/groom-2.jpg', 1, '2025-02-10 14:25:00'),
(4, 4, '/images/bride-2.jpg', 1, '2025-02-15 16:55:00'),
(5, 5, '/images/groom-3.jpg', 1, '2025-03-01 09:30:00'),
(6, 6, '/images/bride-3.jpg', 1, '2025-03-05 12:20:00')
ON DUPLICATE KEY UPDATE `PhotoUrl` = VALUES(`PhotoUrl`);

-- 6. Seed Partner Preferences
INSERT INTO `PartnerPreferences` (`UserProfileId`, `MinAge`, `MaxAge`, `PreferredGender`, `PreferredReligion`, `PreferredMaritalStatus`, `PreferredDivision`, `DietaryPreference`, `Notes`) VALUES
(1, 22, 28, 2, 1, 1, 'Dhaka', 2, 'Prefers an educated and modest partner living in Dhaka'),
(2, 27, 34, 1, 1, 1, 'Dhaka', 2, 'Prefers an established professional engineer or doctor'),
(3, 23, 29, 2, 1, 1, 'Chittagong', 2, 'Family-oriented lady from Chittagong or Dhaka'),
(4, 28, 35, 1, 1, 1, 'Dhaka', 2, 'Educated professional with progressive family values'),
(5, 21, 27, 2, 1, 1, 'Sylhet', 2, 'Kind, friendly companion who appreciates family life'),
(6, 26, 33, 1, 1, 1, 'Dhaka', 2, 'Intellectual, honest, and loving gentleman')
ON DUPLICATE KEY UPDATE `MinAge` = VALUES(`MinAge`);

-- 7. Seed NID Verifications
INSERT INTO `NidVerifications` (`Id`, `UserId`, `NidNumber`, `FrontDocumentUrl`, `BackDocumentUrl`, `Status`, `SubmittedAt`, `ReviewedAt`, `ReviewedByAdminId`, `RejectionReason`) VALUES
(1, 2, '19942691234567890', '/images/sample-nid-front.png', '/images/sample-nid-back.png', 2, '2025-02-01 10:15:00', '2025-02-01 14:00:00', 1, NULL),
(2, 3, '19972691234567891', '/images/sample-nid-front.png', '/images/sample-nid-back.png', 2, '2025-02-05 11:45:00', '2025-02-05 15:30:00', 1, NULL),
(3, 4, '19922691234567892', '/images/sample-nid-front.png', '/images/sample-nid-back.png', 2, '2025-02-10 14:30:00', '2025-02-10 17:00:00', 1, NULL),
(4, 5, '19962691234567893', '/images/sample-nid-front.png', '/images/sample-nid-back.png', 2, '2025-02-15 17:00:00', '2025-02-15 18:30:00', 1, NULL),
(5, 6, '19952691234567894', '/images/sample-nid-front.png', '/images/sample-nid-back.png', 1, '2025-03-01 09:35:00', NULL, NULL, NULL),
(6, 7, '19982691234567895', '/images/sample-nid-front.png', '/images/sample-nid-back.png', 2, '2025-03-05 12:25:00', '2025-03-05 14:10:00', 1, NULL)
ON DUPLICATE KEY UPDATE `Status` = VALUES(`Status`);

-- 8. Seed Sample Success Stories
INSERT INTO `SuccessStories` (`Id`, `CoupleNames`, `StoryTitle`, `StoryDescription`, `PhotoUrl`, `MarriageDate`, `Location`, `Status`, `ApprovedByAdminId`, `CreatedAt`) VALUES
(1, 'Tahsin & Farhana', 'Found My Soulmate in Just 3 Months', 'We both joined Matrimony Hub seeking genuine life partners with aligned Islamic values. After unlocking contacts and having families meet, everything progressed with grace and blessing.', '/images/success-story-1.jpg', '2025-12-10', 'Dhaka, Bangladesh', 2, 1, '2025-12-15 10:00:00'),
(2, 'Saimon & Nazia', 'A Modern Match Rooted in Mutual Respect', 'Finding someone who respects both your career aspirations and family heritage felt daunting until Matrimony Hub. The verified profiles gave our parents absolute peace of mind.', '/images/success-story-2.jpg', '2026-01-15', 'Chittagong, Bangladesh', 2, 1, '2026-01-20 11:00:00'),
(3, 'Zubair & Tasnim', 'From Match Score to Nikah', 'Our 95% match compatibility score proved surprisingly accurate! From mutual interests in travel to shared spiritual values, we couldn''t be happier.', '/images/hero-bangladeshi-couple.jpg', '2026-02-20', 'Sylhet, Bangladesh', 2, 1, '2026-02-25 15:00:00')
ON DUPLICATE KEY UPDATE `CoupleNames` = VALUES(`CoupleNames`);

-- 9. Seed Sample Payment, Transaction, and Unlocked Contact
INSERT INTO `Payments` (`Id`, `UserId`, `TargetProfileId`, `Amount`, `Currency`, `PaymentPurpose`, `TransactionId`, `Gateway`, `GatewayTransactionId`, `Status`, `CreatedAt`, `CompletedAt`) VALUES
(1, 2, 2, 500.00, 'BDT', 1, 'TXN20250212001', 1, 'BK-TRX-2025021201', 3, '2025-02-12 10:00:00', '2025-02-12 10:02:15')
ON DUPLICATE KEY UPDATE `Status` = VALUES(`Status`);

INSERT INTO `Transactions` (`Id`, `PaymentId`, `GatewayTransactionId`, `GatewayResponse`, `Amount`, `Status`, `CreatedAt`) VALUES
(1, 1, 'BK-TRX-2025021201', 'bKash Callback: Successful Tokenized Authorization', 500.00, 3, '2025-02-12 10:02:15')
ON DUPLICATE KEY UPDATE `Amount` = VALUES(`Amount`);

INSERT INTO `ContactAccess` (`Id`, `UserId`, `TargetProfileId`, `PaymentId`, `UnlockedAt`) VALUES
(1, 2, 2, 1, '2025-02-12 10:02:15')
ON DUPLICATE KEY UPDATE `UnlockedAt` = VALUES(`UnlockedAt`);

-- 10. Seed Admin Log
INSERT INTO `AdminLogs` (`AdminUserId`, `Action`, `EntityType`, `EntityId`, `Description`, `IpAddress`, `CreatedAt`) VALUES
(1, 'DATABASE_SEED', 'System', '0', 'Seeded initial application data, roles, demo users and success stories.', '127.0.0.1', '2025-01-01 00:00:00');
